### ISSUE TITLE
other dataset such as celebA will train a result?

### ISSUE THREAD

**Issue by zdx3578** [hvy/chainer-infogan#1]
other dataset such as celebA will train a result?

**Comment by hvy** [comment]
Yes, you should be able to train the network with some minor changes.

First, change the training data (`numpy.ndarray`) loaded in `train.py` from MNIST to CelebA and make sure that all images have the **same width and height**. MNIST is fetched and preprocessed via the Chainer framework which is convenient but this is not the case for CelebA as you probably know.

Second, change the number of **output channels from the generator and inputs channels in the discriminator to 3** if you're working with RGB (it is 1 at the moment because of the single grayscale channel in MNIST). Depending on the width and height of the images you want to generate, you also need to **change the number of output neurons from the first few linear connections** in the generator so that they can be reshaped and upsampled to the desired dimension.
