### ISSUE TITLE
unexpected argument in chainer functions softmax_cross_entropy

### ISSUE THREAD

**Issue by dakshdrolia376** [hvy/chainer-infogan#4]
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    categorical_loss = F.softmax_cross_entropy(mi_categorical, categories, use_cudnn = False)
TypeError: softmax_cross_entropy() got an unexpected keyword argument 'use_cudnn'

Please see the issue.

**Comment by hvy** [comment]
Hi,

This is probably due to to updated interface in Chainer v2.
The code is written with Chainer v1, which is why you are getting that error message.

I will try to fix the bug but meanwhile, please take a look at the official upgrade notes to get around it.
https://docs.chainer.org/en/stable/upgrade.html#configurations-are-added-and-replace-some-of-existing-global-flags
You'll also need to remove the `test` flag from the batch normalization layers, for the same reason.
